//
//  HomeScreenStyleSheet.js
//  RiseApp
//
//  Created by Nikhil Patel.
//  Copyright © 2018 Rise. All rights reserved.
//

import {StyleSheet, Dimensions} from 'react-native';
const PAGE_HEIGHT = Dimensions.get('window').height;
const styles = StyleSheet.create({
  homescreenView: {
    backgroundColor: 'white',
    flex: 1,
    justifyContent: 'flex-end',
  },
  scrollviewScrollView: {
    backgroundColor: 'transparent',
    flex: 1,
  },
  textText: {
    color: 'rgb(29, 103, 153)',
    // fontFamily: "Rubik-Regular",
    fontSize: 36,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
    backgroundColor: 'transparent',
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowRadius: 13,
    elevation: 4,
    shadowOpacity: 1,
    marginLeft: 66,
    marginRight: 66,
  },
  cardDayGroupView: {
    marginTop: 5,
  },
  cardNightGroupView: {
    backgroundColor: '#34495e',
    borderRadius: 41,
    shadowColor: 'rgba(0, 0, 0, 0.5)',
    shadowRadius: 10,
    elevation: 2,
    shadowOpacity: 1,
    height: 950,
    marginTop: 45,
  },
  viewThreeView: {
    backgroundColor: 'transparent',
    height: 175,
    marginLeft: 15,
    marginRight: 15,
    marginTop: PAGE_HEIGHT >= 800 ? '45%' : '25%',
    elevation: 0,
  },
  card1View: {
    backgroundColor: '#fff',
    // backgroundColor: "rgb(58, 160, 254)",
    borderRadius: 15,
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowOffset: {
      height: 1,
    },
    shadowRadius: 10,
    shadowOpacity: 1,
    position: 'absolute',
    left: 0,
    right: 0,
    elevation: 4,
    top: 0,
    height: 175,
    justifyContent: 'center',
    alignItems: 'center',
  },
  timeView: {
    flex: 0.7,
    margin: 10,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    elevation: 4,
    // borderBottomWidth: 1,
    // borderColor: "rgb(252, 102, 129)"
  },
  currentTask: {
    fontSize: 22,
    textAlign: 'center',
    paddingTop: 2,
    fontWeight: '400',
  },
  timeRemaining: {
    fontSize: 16,
    padding: 5,
    fontWeight: '300',
  },
  nextTask: {
    fontSize: 14,
    paddingBottom: 10,
    fontWeight: '300',
  },
  newsText: {
    color: 'black',
    // fontFamily: "Rubik-Regular",
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
    alignItems: 'flex-start',
    backgroundColor: 'transparent',
  },
  card1Container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  urlButtonText: {
    color: 'black',
    fontSize: 25,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
  },
  urlButtonImage: {
    resizeMode: 'contain',
    marginLeft: 62,
  },
  viewTwoView: {
    backgroundColor: 'transparent',
    flex: 1,
    marginTop: 15,
  },
  card2View: {
    backgroundColor: '#fff',
    borderRadius: 15,
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  card2HeaderView: {
    height: 30,
    justifyContent: 'center',
  },
  card2FooterView: {
    // marginVertical: 3,
    height: 20,
  },
  weatherText: {
    backgroundColor: 'transparent',
    color: 'black',
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: '300',
    textAlign: 'center',
  },
  viewView: {
    backgroundColor: 'transparent',
    height: 80,
    marginLeft: 15,
    marginRight: 15,
    marginTop: 20,
  },
  card3View: {
    backgroundColor: '#fff',
    borderRadius: 15,
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowRadius: 10,
    elevation: 4,
    shadowOpacity: 1,
    shadowOffset: {
      height: 1,
    },
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: '100%',
  },
  tryItOutText: {
    color: 'black',
    // fontFamily: "Rubik-Regular",
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
    backgroundColor: 'transparent',
    position: 'absolute',
    left: 111,
    right: 110,
    top: 2,
  },
  card4View: {
    backgroundColor: '#fff',
    borderRadius: 15,
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowRadius: 3,
    elevation: 4,
    shadowOpacity: 1,
    height: 190,
  },
  rectangleView: {
    backgroundColor: 'transparent',
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 727,
  },
  tableviewFlatListViewWrapper: {
    backgroundColor: 'transparent',
    marginHorizontal: 5,
    height: 200,
    alignSelf: 'center',
  },
  noTasksFound: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
    paddingTop: 20,
  },
  tableviewFlatList: {
    backgroundColor: 'transparent',
    paddingTop: 5,
  },
  card1ButtonGroup: {
    flex: 0.3,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-around',
    margin: 10,
    elevation: 4,
  },
  card1Buttons: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#dddddd',
    textAlign: 'center',
    fontSize: 16,
    paddingVertical: 7,
    paddingHorizontal: 5,
    backgroundColor: 'white',
    color: 'blue',
  },
  buttonContainer: {
    shadowColor: 'rgba(0, 0, 0, 0.20)',
    shadowOffset: {
      height: 2,
    },
    shadowRadius: 10,
    shadowOpacity: 1,
    elevation: 4,
  },
  adfreebuttonView: {
    backgroundColor: 'transparent',
    width: 150,
  },
  option4Button: {
    backgroundColor: 'white',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#dddddd',
    shadowColor: 'rgba(0, 0, 0, 0.10)',
    shadowOffset: {
      height: 2,
    },
    shadowRadius: 2,
    elevation: 4,
    shadowOpacity: 1,
    padding: 0,
    paddingVertical: 7,
    paddingHorizontal: 5,
  },
  option4ButtonText: {
    color: 'black',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '500',
    textAlign: 'center',
  },
  notiView: {
    height: 60,
    width: 70,
    // alignSelf: 'flex-end',
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    position: 'absolute',
    // elevation: 4,
    top: PAGE_HEIGHT >= 800 ? 50 : 20,
    right: 20,
    zIndex: 3,
  },
  notiButton: {
    height: 50,
    width: 50,
    backgroundColor: 'transparent',
    borderRadius: 15,
    shadowColor: 'rgba(0, 0, 0, 0.20)',
    shadowOffset: {
      height: 2,
    },
    shadowRadius: 10,
    elevation: 4,
    shadowOpacity: 1,
    marginTop: 10,
    marginRight: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  counter: {
    height: 25,
    width: 25,
    backgroundColor: 'red',
    borderRadius: 25 / 2,
    elevation: 4,
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  counterText: {
    fontWeight: '800',
    textAlign: 'center',
    color: 'white',
    fontSize: 16,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    paddingTop: 120,
  },
  modalView: {
    backgroundColor: 'white',
    borderRadius: 10,
    width: '95%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    height: 250,
    // marginHorizontal: 10,
  },
  closeButton: {
    alignSelf: 'flex-end',
    paddingTop: 5,
    paddingRight: 10,
  },
  textStyle: {
    height: 30,
    width: 30,
    resizeMode: 'contain',
  },
  messageView: {
    height: 80,
    borderWidth: 1,
    borderColor: '#dddddd',
    padding: 10,
  },
  messageText: {
    fontSize: 16,
    color: 'black',
    textAlign: 'left',
    // width: '90%',
    flex: 1,
    flexWrap: 'wrap',
  },
});

export default styles;
