//
//  ProfileStyleSheet.js
//  RiseApp
//
//  Created by Nikhil Patel.
//  Copyright © 2018 Rise. All rights reserved.
//

import {StyleSheet} from 'react-native';

const labelColor = 'black';
const textColor = '#2969FB';
const lineColor = '#7A5FFA';
const buttonColor = '#7A5FFA';

const styles = StyleSheet.create({
  profileView: {
    backgroundColor: '#DEE9FD', //"rgb(231, 238, 251)",
    flex: 1,
  },
  backbuttonbarView: {
    backgroundColor: 'transparent',
    height: 58,
    alignItems: 'flex-start',
  },
  backbuttonButton: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    width: 39,
    height: 28,
    marginLeft: 11,
    marginTop: 40,
  },
  backbuttonButtonText: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  backbuttonButtonImage: {
    resizeMode: 'contain',
  },
  profileText: {
    color: 'rgb(29, 103, 153)',
    // fontFamily: "Rubik-Regular",
    fontSize: 48,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
    backgroundColor: 'transparent',
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowRadius: 4,
    elevation: 4,
    shadowOpacity: 1,
    alignSelf: 'center',
    marginTop: 12,
  },
  rectangleView: {
    backgroundColor: '#fff',
    borderRadius: 41,
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowRadius: 7,
    elevation: 4,
    shadowOpacity: 1,
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: -50,
  },
  spinner: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    zIndex: 2,
  },
  daypickerView: {
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowRadius: 7,
    elevation: 4,
    shadowOpacity: 1,
    shadowOffset: {
      height: 1,
    },
    backgroundColor: '#F4F2FF',
    borderRadius: 15,
    alignSelf: 'center',
    width: 333,
    height: 52,
  },
  daybuttonsuView: {
    backgroundColor: 'transparent',
    width: 39,
    height: 36,
  },
  ovalButton: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    height: 36,
  },
  ovalButtonText: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  ovalButtonImage: {
    resizeMode: 'contain',
  },
  suText: {
    color: 'white',
    // fontFamily: "Rubik-Regular",
    fontSize: 13,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
    letterSpacing: 1.61,
    backgroundColor: 'transparent',
    marginLeft: 9,
    marginRight: 9,
  },
  daybuttonmView: {
    backgroundColor: 'transparent',
    width: 39,
    height: 36,
    marginLeft: 5,
  },
  ovalTwoButton: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    height: 36,
  },
  ovalTwoButtonImage: {
    resizeMode: 'contain',
  },
  ovalTwoButtonText: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  mText: {
    color: 'white',
    // fontFamily: "Rubik-Regular",
    fontSize: 13,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
    letterSpacing: 1.61,
    backgroundColor: 'transparent',
    marginLeft: 13,
    marginRight: 13,
  },
  daybuttontView: {
    backgroundColor: 'transparent',
    width: 39,
    height: 36,
    marginLeft: 5,
  },
  ovalThreeButton: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    height: 36,
  },
  ovalThreeButtonText: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  ovalThreeButtonImage: {
    resizeMode: 'contain',
  },
  tText: {
    color: 'white',
    // fontFamily: "Rubik-Regular",
    fontSize: 13,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
    letterSpacing: 1.61,
    backgroundColor: 'transparent',
    marginLeft: 15,
    marginRight: 14,
  },
  daybuttonthView: {
    backgroundColor: 'transparent',
    width: 39,
    height: 36,
    marginRight: 5,
  },
  ovalFiveButton: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    height: 36,
  },
  ovalFiveButtonImage: {
    resizeMode: 'contain',
  },
  ovalFiveButtonText: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  thText: {
    backgroundColor: 'transparent',
    color: 'white',
    // fontFamily: "Rubik-Regular",
    fontSize: 13,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
    letterSpacing: 1.61,
    marginLeft: 5,
    marginRight: 5,
  },
  daybuttonfView: {
    backgroundColor: 'transparent',
    width: 39,
    height: 36,
    marginRight: 5,
  },
  ovalSixButton: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    height: 36,
  },
  ovalSixButtonText: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  ovalSixButtonImage: {
    resizeMode: 'contain',
  },
  fText: {
    backgroundColor: 'transparent',
    color: 'white',
    // fontFamily: "Rubik-Regular",
    fontSize: 13,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
    letterSpacing: 1.61,
    marginLeft: 14,
    marginRight: 14,
  },
  daybuttonsView: {
    backgroundColor: 'transparent',
    width: 39,
    height: 36,
  },
  ovalSevenButton: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    height: 36,
  },
  ovalSevenButtonImage: {
    resizeMode: 'contain',
  },
  ovalSevenButtonText: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  sText: {
    backgroundColor: 'transparent',
    color: 'white',
    // fontFamily: "Rubik-Regular",
    fontSize: 13,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
    letterSpacing: 1.61,
    marginLeft: 14,
    marginRight: 14,
  },
  daybuttonwView: {
    backgroundColor: 'transparent',
    width: 39,
    height: 36,
  },
  ovalFourButton: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    height: 36,
  },
  ovalFourButtonImage: {
    resizeMode: 'contain',
  },
  ovalFourButtonText: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  wText: {
    backgroundColor: 'transparent',
    color: 'white',
    // fontFamily: "Rubik-Regular",
    fontSize: 13,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
    marginLeft: 13,
    marginRight: 13,
  },
  infocardView: {
    backgroundColor: 'transparent',
    borderRadius: 21,
    // borderWidth: 1,
    borderColor: 'rgb(252, 102, 129)',
    borderStyle: 'solid',
    alignSelf: 'stretch',
    // height: 370,
    marginLeft: 5,
    marginRight: 5,
    marginTop: 18,
    paddingBottom: 5,
  },
  timepickerView: {
    backgroundColor: 'transparent',
    alignSelf: 'center',
    // width: 115,
    height: 77,
    // marginLeft: 12,
    marginTop: 13,
  },
  datepickerView: {
    backgroundColor: 'transparent',
    alignSelf: 'center',
    height: 77,
    marginTop: 0,
  },
  arrivalTimeText: {
    color: 'black',
    // fontFamily: "Poppins-Regular",
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '400',
    textAlign: 'center',
    letterSpacing: 0.16,
    backgroundColor: 'transparent',
    marginRight: 1,
  },
  textInputTextInput: {
    backgroundColor: 'transparent',
    padding: 0,
    color: '#2969FB',
    // fontFamily: "Poppins-Regular",
    fontSize: 36,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
    height: 46,
    // marginLeft: 4,
    // marginRight: 1,
    marginTop: 3,
  },
  lineView: {
    backgroundColor: '#7A5FFA',
    height: 1,
  },
  destinationView: {
    backgroundColor: 'transparent',
    height: 56,
    alignItems: 'center',
    marginLeft: 12,
    marginRight: 15,
    marginTop: 24,
  },
  destinationText: {
    color: labelColor,
    // fontFamily: "Poppins-Regular",
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '400',
    textAlign: 'center',
    letterSpacing: 0.16,
    backgroundColor: 'transparent',
    alignSelf: 'center',
  },
  addressTextInput: {
    color: textColor,
    // fontFamily: "Poppins-Regular",
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
    backgroundColor: 'transparent',
    padding: 0,
    height: 23,
    marginLeft: 7,
    // alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: lineColor,
  },
  rectangleTwoView: {
    backgroundColor: 'transparent',
    borderRadius: 3,
    borderWidth: 1,
    borderColor: 'rgb(135, 199, 255)',
    borderStyle: 'solid',
    position: 'absolute',
    left: 0,
    right: 3,
    top: 26,
    height: 30,
  },
  currentlocationView: {
    backgroundColor: 'transparent',
    height: 56,
    marginLeft: 12,
    marginRight: 15,
    marginTop: 24,
  },
  startLocationText: {
    color: 'black',
    // fontFamily: "Poppins-Regular",
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '400',
    textAlign: 'center',
    letterSpacing: 0.16,
    backgroundColor: 'transparent',
    alignItems: 'center',
  },
  addressTwoTextInput: {
    color: textColor,
    // fontFamily: "Poppins-Regular",
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
    backgroundColor: 'transparent',
    padding: 0,
    alignSelf: 'stretch',
    height: 24,
    marginLeft: 7,
    marginTop: 7,
    borderBottomWidth: 1,
    borderColor: lineColor,
  },
  rectangleThreeView: {
    backgroundColor: 'transparent',
    borderRadius: 3,
    borderWidth: 1,
    borderColor: 'rgb(135, 199, 255)',
    borderStyle: 'solid',
    position: 'absolute',
    left: 0,
    right: 0,
    top: 26,
    height: 30,
  },
  transmodeView: {
    backgroundColor: 'transparent',
    alignSelf: 'center',
    width: 264,
    height: 83,
    marginBottom: 11,
    marginTop: 15,
  },
  transportionModeText: {
    color: labelColor,
    // fontFamily: "Rubik-Regular",
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '400',
    textAlign: 'center',
    letterSpacing: 0.16,
    backgroundColor: 'transparent',
    alignSelf: 'center',
    marginLeft: 2,
    marginBottom: 3,
  },
  rectangleFourView: {
    backgroundColor: '#F4F2FF',
    borderRadius: 13,
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowRadius: 7,
    elevation: 4,
    shadowOpacity: 1,
    shadowOffset: {
      height: 1,
    },
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 50,
  },
  carButton: {
    backgroundColor: 'rgb(231, 238, 251)',
    borderRadius: 22.5,
    shadowRadius: 9,
    elevation: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    width: 45,
    height: 45,
  },
  carButtonPressed: {
    backgroundColor: '#FC6681',
    borderRadius: 22.5,
    shadowRadius: 9,
    elevation: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    width: 45,
    height: 45,
  },
  carButtonText: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  carButtonImage: {
    resizeMode: 'contain',
  },
  trainButton: {
    backgroundColor: 'rgb(231, 238, 251)',
    borderRadius: 22.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    padding: 0,
    width: 45,
    height: 45,
    marginLeft: 19,
  },
  trainButtonPressed: {
    backgroundColor: '#FC6681',
    borderRadius: 22.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    width: 45,
    height: 45,
    marginLeft: 19,
  },
  trainButtonText: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  trainButtonImage: {
    resizeMode: 'contain',
  },
  bikingButton: {
    backgroundColor: 'rgb(231, 238, 251)',
    borderRadius: 22.5,
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 4,
    justifyContent: 'center',
    padding: 0,
    width: 45,
    height: 45,
    marginRight: 19,
  },
  bikingButtonPressed: {
    backgroundColor: '#FC6681',
    borderRadius: 22.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    width: 45,
    height: 45,
    marginRight: 19,
  },
  bikingButtonText: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  bikingButtonImage: {
    resizeMode: 'contain',
  },
  walkingButton: {
    backgroundColor: 'rgb(231, 238, 251)',
    borderRadius: 22.5,
    flexDirection: 'row',
    elevation: 4,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    width: 45,
    height: 45,
  },
  walkingButtonPressed: {
    backgroundColor: '#FC6681',
    borderRadius: 22.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    width: 45,
    height: 45,
  },
  walkingButtonText: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  walkingButtonImage: {
    resizeMode: 'contain',
  },
  savebuttonButtonAnimated: {
    width: 234,
    height: 46,
  },
  savebuttonButton: {
    backgroundColor: buttonColor,
    borderRadius: 23,
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowRadius: 15,
    elevation: 4,
    shadowOpacity: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    width: '100%',
    height: '100%',
  },
  savebuttonButtonText: {
    color: 'rgb(250, 252, 252)',
    // fontFamily: "Poppins-Regular",
    fontSize: 26,
    fontStyle: 'normal',
    fontWeight: '500',
    textAlign: 'left',
  },
  savebuttonButtonImage: {
    resizeMode: 'contain',
    marginRight: 10,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    // marginTop: 22,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    // width: '80%'
  },
  centeredAddressView: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    // marginTop: 22,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    // width: '80%'
  },
  modalView: {
    marginHorizontal: 20,
    // backgroundColor: 'white',
    borderRadius: 20,
    padding: 25,
    width: '85%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    backgroundColor: 'white',
  },
  modalAddressView: {
    marginHorizontal: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    paddingVertical: 20,
    paddingHorizontal: 5,
    width: '98%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    marginTop: 70,
    // backgroundColor: 'rgb(231, 238, 251)',
    height: 400,
  },
  openButton: {
    backgroundColor: buttonColor,
    borderRadius: 20,
    padding: 10,
    elevation: 2,
    width: '70%',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  textStyleAddress: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 10,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '500',
    alignSelf: 'center',
  },
  moreOptionsText: {
    color: 'rgb(29, 103, 153)',
    // fontFamily: "Rubik-Regular",
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '300',
    textAlign: 'center',
    letterSpacing: 0.16,
    backgroundColor: 'transparent',
    alignSelf: 'center',
    padding: 3,
  },
  profilePickerContainer: {
    flex: 1,
    alignItems: 'center',
    // bottom: 15,
    // justifyContent: 'space-around'
  },
  riselogoImageAnimated: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  transitView: {
    marginBottom: 20,
    padding: 5,
  },
  transitText: {
    fontSize: 20,
    fontWeight: '500',
    color: 'white',
    textAlign: 'center',
  },
  transitButton: {
    backgroundColor: buttonColor,
    borderRadius: 15,
    padding: 10,
    elevation: 2,
    width: 200,
    alignSelf: 'center',
    margin: 5,
  },
});

export default styles;
