//
//  ProfileStyleSheet.js
//  RiseApp
//
//  Created by Nikhil Patel.
//  Copyright © 2018 Rise. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({

	rectangleView: {
		backgroundColor: "#fff",
		borderRadius: 41,
		shadowColor: "rgba(0, 0, 0, 0.1)",
		shadowRadius: 10,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		bottom: -50,
	},
	daypickerView: {
		// shadowColor: "rgba(0, 0, 0, 0.15)",
		// shadowRadius: 5,
		// shadowOpacity: 1,
		backgroundColor: "#fff",
		shadowOffset: {
			height: 2,
		},
		// borderWidth: 1,
		borderColor: "rgb(29, 103, 153)",
		borderRadius: 15,
		alignSelf: "center",
		width: 333,
		height: 52,
	},
	daybuttonsuView: {
		backgroundColor: "transparent",
		width: 39,
		height: 36,
	},
	ovalButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		height: 36,
	},
	ovalButtonText: {
		color: "black",
		fontFamily: ".AppleSystemUIFont",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	ovalButtonImage: {
		resizeMode: "contain",
	},
	suText: {
		color: "white",
		// fontFamily: "Rubik-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		letterSpacing: 1.61,
		backgroundColor: "transparent",
		marginLeft: 9,
		marginRight: 9,
	},
	daybuttonmView: {
		backgroundColor: "transparent",
		width: 39,
		height: 36,
		marginLeft: 5,
	},
	ovalTwoButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		height: 36,
	},
	ovalTwoButtonImage: {
		resizeMode: "contain",
	},
	ovalTwoButtonText: {
		color: "black",
		fontFamily: ".AppleSystemUIFont",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	mText: {
		color: "white",
		// fontFamily: "Rubik-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		letterSpacing: 1.61,
		backgroundColor: "transparent",
		marginLeft: 13,
		marginRight: 13,
	},
	daybuttontView: {
		backgroundColor: "transparent",
		width: 39,
		height: 36,
		marginLeft: 5,
	},
	ovalThreeButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		height: 36,
	},
	ovalThreeButtonText: {
		color: "black",
		fontFamily: ".AppleSystemUIFont",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	ovalThreeButtonImage: {
		resizeMode: "contain",
	},
	tText: {
		color: "white",
		// fontFamily: "Rubik-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		letterSpacing: 1.61,
		backgroundColor: "transparent",
		marginLeft: 15,
		marginRight: 14,
	},
	daybuttonthView: {
		backgroundColor: "transparent",
		width: 39,
		height: 36,
		marginRight: 5,
	},
	ovalFiveButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		height: 36,
	},
	ovalFiveButtonImage: {
		resizeMode: "contain",
	},
	ovalFiveButtonText: {
		color: "black",
		fontFamily: ".AppleSystemUIFont",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	thText: {
		backgroundColor: "transparent",
		color: "white",
		// fontFamily: "Rubik-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		letterSpacing: 1.61,
		marginLeft: 5,
		marginRight: 5,
	},
	daybuttonfView: {
		backgroundColor: "transparent",
		width: 39,
		height: 36,
		marginRight: 5,
	},
	ovalSixButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		height: 36,
	},
	ovalSixButtonText: {
		color: "black",
		fontFamily: ".AppleSystemUIFont",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	ovalSixButtonImage: {
		resizeMode: "contain",
	},
	fText: {
		backgroundColor: "transparent",
		color: "white",
		// fontFamily: "Rubik-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		letterSpacing: 1.61,
		marginLeft: 14,
		marginRight: 14,
	},
	daybuttonsView: {
		backgroundColor: "transparent",
		width: 39,
		height: 36,
	},
	ovalSevenButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		height: 36,
	},
	ovalSevenButtonImage: {
		resizeMode: "contain",
	},
	ovalSevenButtonText: {
		color: "black",
		fontFamily: ".AppleSystemUIFont",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	sText: {
		backgroundColor: "transparent",
		color: "white",
		// fontFamily: "Rubik-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		letterSpacing: 1.61,
		marginLeft: 14,
		marginRight: 14,
	},
	daybuttonwView: {
		backgroundColor: "transparent",
		width: 39,
		height: 36,
	},
	ovalFourButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		height: 36,
	},
	ovalFourButtonImage: {
		resizeMode: "contain",
	},
	ovalFourButtonText: {
		color: "black",
		fontFamily: ".AppleSystemUIFont",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	wText: {
		backgroundColor: "transparent",
		color: "white",
		// fontFamily: "Rubik-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		marginLeft: 13,
		marginRight: 13,
	},
	infocardView: {
		backgroundColor: "transparent",
		borderRadius: 21,
		borderWidth: 1,
		borderColor: "rgb(252, 102, 129)",
		borderStyle: "solid",
		alignSelf: "stretch",
		height: 366,
		marginLeft: 5,
		marginRight: 5,
		marginTop: 18,
	},
	timepickerView: {
		backgroundColor: "transparent",
		alignSelf: "center",
		// width: 115,
		height: 77,
		// marginLeft: 12,
		marginTop: 13,
	},
	arrivalTimeText: {
		color: "rgb(29, 103, 153)",
		// fontFamily: "Poppins-Regular",
		fontSize: 18,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		letterSpacing: 0.16,
		backgroundColor: "transparent",
		marginRight: 1,
	},
	textInputTextInput: {
		backgroundColor: "transparent",
		padding: 0,
		color: "rgb(29, 103, 153)",
		// fontFamily: "Poppins-Regular",
		fontSize: 36,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		height: 46,
		// marginLeft: 4,
		// marginRight: 1,
		marginTop: 3,
	},
	lineView: {
		backgroundColor: "rgb(252, 102, 129)",
		height: 1,
	},
	destinationView: {
		backgroundColor: "transparent",
		height: 56,
		alignItems: 'center',
		marginLeft: 12,
		marginRight: 15,
		marginTop: 24,
	},
	destinationText: {
		color: "rgb(29, 103, 153)",
		// fontFamily: "Poppins-Regular",
		fontSize: 18,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		letterSpacing: 0.16,
		backgroundColor: "transparent",
		alignSelf: "center",
	},
	addressTextInput: {
		color: "rgb(29, 103, 153)",
		// fontFamily: "Poppins-Regular",
		fontSize: 18,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		padding: 0,
		height: 23,
		marginLeft: 7,
		// alignItems: 'center',
		borderBottomWidth: 1,
		borderColor: "rgb(252, 102, 129)",
	},
	rectangleTwoView: {
		backgroundColor: "transparent",
		borderRadius: 3,
		borderWidth: 1,
		borderColor: "rgb(135, 199, 255)",
		borderStyle: "solid",
		position: "absolute",
		left: 0,
		right: 3,
		top: 26,
		height: 30,
	},
	rectangleThreeView: {
		backgroundColor: "transparent",
		borderRadius: 3,
		borderWidth: 1,
		borderColor: "rgb(135, 199, 255)",
		borderStyle: "solid",
		position: "absolute",
		left: 0,
		right: 0,
		top: 26,
		height: 30,
	},
	transmodeView: {
		backgroundColor: "transparent",
		alignSelf: "center",
		width: 264,
		height: 83,
		marginBottom: 11,
		marginTop: 11
	}
})

export default styles
