//
//  ResetPasswordStyleSheet.js
//  RiseApp
//
//  Created by Nikhil Patel.
//  Copyright © 2018 Rise. All rights reserved.
//

import {StyleSheet} from 'react-native';

const buttonColor = '#7A5FFA';

const styles = StyleSheet.create({
  resetpasswordView: {
    backgroundColor: 'rgba(176,196,222, 1)',
    flex: 1,
  },
  backbuttonbarView: {
    backgroundColor: 'transparent',
    height: 58,
    alignItems: 'flex-start',
  },
  riselogoImageAnimated: {
    width: 250,
    height: 190,
    alignSelf: 'center',
  },
  riselogoImage: {
    backgroundColor: 'transparent',
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
    shadowColor: 'rgba(0, 0, 0, 0.4)',
    shadowRadius: 3,
    shadowOpacity: 1,
    shadowOffset: {
      height: 0,
    },
  },
  backbuttonButtonText: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  backbuttonButton: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    width: 39,
    height: 28,
    marginLeft: 11,
    marginTop: 40,
  },
  backbuttonButtonImage: {
    resizeMode: 'contain',
  },
  rectangleView: {
    backgroundColor: '#fff',
    borderRadius: 41,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowRadius: 10,
    shadowOpacity: 1,
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  viewScrollView: {
    backgroundColor: 'transparent',
    flex: 1,
    marginBottom: 38,
  },
  labelText: {
    backgroundColor: 'transparent',
    color: 'rgb(29, 103, 153)',
    // fontFamily: "Rubik-Regular",
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
    alignSelf: 'center',
    marginTop: 21,
  },
  infocardView: {
    backgroundColor: 'transparent',
    borderRadius: 21,
    // borderWidth: 1,
    borderColor: 'rgb(135, 199, 255)',
    borderStyle: 'solid',
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 354,
  },
  emailView: {
    backgroundColor: 'transparent',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    // borderColor: 'black',
    // borderWidth: 1,
  },
  formFieldTwoView: {
    backgroundColor: 'rgb(225, 230, 235)',
    borderRadius: 20.31,
    borderWidth: 1,
    borderColor: 'rgb(198, 217, 227)',
    borderStyle: 'solid',
    position: 'absolute',
    left: 0,
    right: 0,
    top: 17,
    height: 42,
    width: '80%',
  },
  emailAddressText: {
    backgroundColor: 'rgb(225, 230, 235)',
    color: 'rgba(161, 159, 159, 0.8)',
    // fontFamily: "Poppins-SemiBold",
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'bold',
    textAlign: 'left',
    alignSelf: 'flex-start',
  },
  emailAddressTextInput: {
    backgroundColor: 'rgb(225, 230, 235)',
    paddingHorizontal: 16,
    color: 'rgb(8, 9, 9)',
    // fontFamily: "Rubik-Regular",
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
    marginTop: 7,
    height: 42,
    borderRadius: 20.31,
    borderWidth: 1,
    borderColor: '#fff',
    width: '95%',
  },
  confirmpasswordView: {
    backgroundColor: 'transparent',
    flex: 1,
  },
  formFieldView: {
    backgroundColor: 'rgb(225, 230, 235)',
    borderRadius: 20.31,
    borderWidth: 1,
    borderColor: 'rgb(198, 217, 227)',
    borderStyle: 'solid',
    position: 'absolute',
    left: 0,
    right: 0,
    top: 17,
    height: 42,
  },
  passwordText: {
    backgroundColor: 'transparent',
    color: 'rgba(161, 159, 159, 0.8)',
    // fontFamily: "Poppins-SemiBold",
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'bold',
    textAlign: 'left',
    alignSelf: 'flex-start',
    marginLeft: 1,
  },
  passwordTextInput: {
    backgroundColor: 'transparent',
    padding: 0,
    color: 'rgb(8, 9, 9)',
    // fontFamily: "Rubik-Regular",
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
    height: 19,
    marginTop: 8,
  },
  formFieldCopyView: {
    backgroundColor: 'rgb(225, 230, 235)',
    borderRadius: 20.31,
    borderWidth: 1,
    borderColor: 'rgb(198, 217, 227)',
    borderStyle: 'solid',
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 42,
  },
  confirmPasswordText: {
    backgroundColor: 'transparent',
    color: 'red',
    // fontFamily: "Poppins-SemiBold",
    fontSize: 20,
    fontStyle: 'normal',
    fontWeight: 'bold',
    textAlign: 'left',
    alignSelf: 'center',
    padding: 5,
  },
  pTextInput: {
    color: 'rgb(8, 9, 9)',
    // fontFamily: "Rubik-Regular",
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
    backgroundColor: 'transparent',
    padding: 0,
    height: 19,
  },
  signupButton: {
    backgroundColor: buttonColor,
    borderRadius: 25,
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowRadius: 29,
    shadowOpacity: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    alignSelf: 'center',
    width: 179,
    height: 50,
  },
  signupButtonText: {
    color: 'rgb(252, 248, 248)',
    // fontFamily: "Rubik-Regular",
    fontSize: 20,
    fontStyle: 'normal',
    fontWeight: '500',
    textAlign: 'center',
  },
  signupButtonImage: {
    resizeMode: 'contain',
    marginRight: 10,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    // marginTop: 22,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    // width: '80%'
  },
  modalView: {
    marginHorizontal: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 25,
    width: '85%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    // backgroundColor: 'rgb(231, 238, 251)',
  },
  modalText: {
    marginBottom: 10,
    textAlign: 'center',
    fontSize: 18,
    color: 'black',
    fontWeight: '500',
  },
  openButton: {
    backgroundColor: buttonColor,
    borderRadius: 20,
    padding: 10,
    elevation: 2,
    width: '70%',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  emailImage: {
    resizeMode: 'contain',
  },
});

export default styles;
