//
//  LoginScreenStyleSheet.js
//  RiseApp
//
//  Created by Nikhil Patel.
//  Copyright © 2018 Rise. All rights reserved.
//

import {StyleSheet} from 'react-native';

const buttonColor = '#7A5FFA';

const styles = StyleSheet.create({
  loginscreenView: {
    backgroundColor: 'rgba(176,196,222, 1)',
    flex: 1,
    alignItems: 'center',
  },
  spinner: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  welcomeToRiseText: {
    color: 'rgb(20, 37, 80)',
    fontSize: 26,
    fontStyle: 'normal',
    fontWeight: '500',
    textAlign: 'left',
    letterSpacing: 0.25,
    backgroundColor: 'transparent',
    alignSelf: 'center',
  },
  riselogoImage: {
    backgroundColor: 'transparent',
    // resizeMode: "cover",
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
    shadowColor: 'rgba(0, 0, 0, 0.4)',
    shadowRadius: 4,
    shadowOpacity: 1,
    shadowOffset: {
      height: 0,
    },
  },
  riselogoImageAnimated: {
    // position: "absolute",
    // alignSelf: "center",
    // width: 256,
    // top: 10,
    // height: 200,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
  },
  emailView: {
    backgroundColor: 'transparent',
    width: '85%',
    marginLeft: 25,
    marginRight: 25,
    // borderWidth: 2,
  },
  formFieldTwoView: {
    backgroundColor: 'rgba(225, 230, 235, 0.7)',
    borderRadius: 20.31,
    borderWidth: 1,
    borderColor: '#FFF',
    borderStyle: 'solid',
    position: 'absolute',
    left: 0,
    right: 0,
    top: 17,
    height: 40,
  },
  emailAddressText: {
    backgroundColor: 'transparent',
    color: buttonColor,
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 'bold',
    textAlign: 'left',
    marginLeft: 10,
  },
  emailAddressTextInput: {
    paddingHorizontal: 10,
    color: 'rgb(8, 9, 9)',
    fontSize: 18,
    textAlign: 'left',
    marginTop: 5,
    backgroundColor: 'rgba(225, 230, 235, 0.7)',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#FFF',
    borderStyle: 'solid',
    height: 42,
    // width: '85%',
  },
  passwordView: {
    backgroundColor: 'transparent',
    marginLeft: 25,
    marginRight: 25,
    width: '85%',
    marginTop: 10,
    // borderWidth: 2,
    // justifyContent: 'center',
    alignSelf: 'center',
    flex: 0.5,
  },
  formFieldView: {
    backgroundColor: 'rgba(225, 230, 235, 0.70)',
    borderRadius: 20.31,
    borderWidth: 1,
    // borderColor: "rgb(198, 217, 227)",
    borderColor: '#FFF',
    borderStyle: 'solid',
    position: 'absolute',
    left: 0,
    right: 0,
    top: 17,
    height: 42,
  },
  passwordText: {
    color: 'rgba(161, 159, 159, 0.8)',
    // fontFamily: "Poppins-SemiBold",
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'bold',
    textAlign: 'left',
    backgroundColor: 'transparent',
  },
  forgotPasswordButton: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    width: 125,
    height: 15,
  },
  forgotPasswordButtonText: {
    color: 'rgb(20, 37, 80)',
    // fontFamily: "Poppins-Regular",
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
    paddingBottom: 2,
  },
  forgotPasswordButtonImage: {
    resizeMode: 'contain',
    marginRight: 10,
  },
  passwordTextInput: {
    color: 'rgb(8, 9, 9)',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
    paddingHorizontal: 10,
    // marginRight: 10,
    // marginTop: 5,
    backgroundColor: 'rgba(225, 230, 235, 0.70)',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#FFF',
    borderStyle: 'solid',
    height: 42,
    // width: '85%',
  },
  loginbuttonButtonAnimated: {
    width: 179,
    height: 50,
    marginBottom: 31,
  },
  loginbuttonButton: {
    backgroundColor: buttonColor,
    borderRadius: 25,
    shadowColor: 'rgba(0, 0, 0, 0.29)',
    shadowRadius: 5,
    elevation: 4,
    shadowOpacity: 1,
    shadowOffset: {
      height: 2,
    },
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    width: '100%',
    height: '100%',
    marginTop: 8,
  },
  loginbuttonButtonText: {
    color: 'rgb(252, 248, 248)',
    // fontFamily: "Rubik-Regular",
    fontSize: 22,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
  },
  loginbuttonButtonImage: {
    resizeMode: 'contain',
    marginRight: 10,
  },
  googlebuttonButtonAnimated: {
    width: 260,
    height: 47,
    marginBottom: 33,
  },
  googlebuttonButton: {
    backgroundColor: 'rgba(0, 145, 255, 0.87)',
    borderRadius: 23.5,
    shadowColor: 'rgba(0, 0, 0, 0.4)',
    shadowRadius: 3,
    elevation: 4,
    shadowOpacity: 1,
    shadowOffset: {
      height: 2,
    },
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    width: '100%',
    height: '100%',
  },
  googlebuttonButtonText: {
    color: 'white',
    // fontFamily: "Rubik-Regular",
    fontSize: 20,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
  },
  googlebuttonButtonImage: {
    resizeMode: 'contain',
    marginRight: 10,
  },
  dontHaveAnAccountButtonImage: {
    resizeMode: 'contain',
    marginRight: 10,
  },
  dontHaveAnAccountButtonAnimated: {
    width: 285,
    height: 27,
  },
  dontHaveAnAccountButton: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    width: '100%',
    height: '100%',
  },
  dontHaveAnAccountButtonText: {
    color: 'rgb(20, 37, 80)',
    // fontFamily: "Poppins-Regular",
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
});

export default styles;
