//
//  SplashScreenStyleSheet.js
//  RiseApp
//
//  Created by Nikhil Patel.
//  Copyright © 2018 Rise. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	splashscreenView: {
		backgroundColor: "rgba(176,196,222, 1)",
		flex: 1,
	},
	riselogoView: {
		backgroundColor: "transparent",
		width: "70%",
		height: "70%",
		alignItems: "center",
		justifyContent: 'center'
	},
	riselogoViewAnimated: {
		// height: 395,
		// marginLeft: 6,
		// marginRight: 6,
		// marginTop: 214,
		flex: 1,
		alignItems: 'center',
		justifyContent: "center",
	},
	riselogoImage: {
		backgroundColor: "transparent",
		// resizeMode: "cover",
		width: "100%",
		height: "100%",
		resizeMode: "contain",
		shadowColor: "rgba(0, 0, 0, 0.4)",
		shadowRadius: 4,
		shadowOpacity: 1,
		shadowOffset: {
			height: 0
		},
	},
	fill1Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.47)",
		shadowRadius: 4,
		shadowOpacity: 1,
		width: 20,
		height: 41,
		marginTop: 33,
	},
	fill2Image: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.47)",
		shadowRadius: 4,
		shadowOpacity: 1,
		resizeMode: "center",
		width: 19,
		height: 68,
		marginLeft: 11,
	},
	fill3Image: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.47)",
		shadowRadius: 4,
		shadowOpacity: 1,
		resizeMode: "center",
		width: 55,
		height: 55,
		marginTop: 4,
	},
	fill4Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.47)",
		shadowRadius: 4,
		shadowOpacity: 1,
		width: 23,
		height: 40,
		marginLeft: 70,
	},
	fill6Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.47)",
		shadowRadius: 4,
		shadowOpacity: 1,
		width: 68,
		height: 19,
		marginTop: 95,
	},
	fill5Image: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.47)",
		shadowRadius: 4,
		shadowOpacity: 1,
		resizeMode: "center",
		position: "absolute",
		right: 123,
		width: 55,
		top: 4,
		height: 55,
	},
	fill8Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.47)",
		shadowRadius: 4,
		shadowOpacity: 1,
		width: 40,
		height: 23,
		marginLeft: 34,
	},
	fill9Image: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.5)",
		shadowRadius: 4,
		shadowOpacity: 1,
		resizeMode: "cover",
		alignSelf: "stretch",
		width: null,
		height: 74,
		marginTop: 17,
	},
	fill12Image: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.47)",
		shadowRadius: 4,
		shadowOpacity: 1,
		resizeMode: "center",
		width: 68,
		height: 15,
	},
	fill10Image: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.5)",
		shadowRadius: 4,
		shadowOpacity: 1,
		resizeMode: "cover",
		alignSelf: "center",
		width: 312,
		height: 93,
		marginTop: 13,
	},
	fill11Image: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.5)",
		shadowRadius: 4,
		shadowOpacity: 1,
		resizeMode: "center",
		position: "absolute",
		left: 75,
		width: 132,
		top: 38,
		height: 88,
	},
	fill7Image: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.47)",
		shadowRadius: 4,
		shadowOpacity: 1,
		resizeMode: "center",
		position: "absolute",
		right: 115,
		width: 41,
		top: 101,
		height: 20,
	},
	riseText: {
		color: "rgb(20, 37, 80)",
		fontSize: 72,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
	},
})

export default styles
