//
//  EditTaskStyleSheet.js
//  RiseApp
//
//  Created by Nikhil Patel.
//  Copyright © 2018 Rise. All rights reserved.
//

import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  edittaskView: {
    backgroundColor: '#DEE9FD', //"rgb(231, 238, 251)",
    flex: 1,
  },
  viewView: {
    backgroundColor: 'transparent',
    height: 58,
    alignItems: 'flex-start',
  },
  backbuttonButton: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    width: 39,
    height: 28,
    marginLeft: 11,
    marginTop: 40,
  },
  backbuttonButtonText: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  backbuttonButtonImage: {
    resizeMode: 'contain',
  },
  backgroundcardView: {
    // backgroundColor: 'rgb(135, 199, 255)',
    // borderRadius: 38,
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowRadius: 7,
    shadowOpacity: 1,
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 559,
    // width: '100%',
    // borderWidth: 2,
  },
  taskiconImage: {
    resizeMode: 'center',
    backgroundColor: 'transparent',
    width: '100%',
    height: '100%',
  },
  taskiconImageAnimated: {
    width: 58,
    height: 85,
  },
  rectangleView: {
    backgroundColor: '#fff',
    borderRadius: 41,
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowRadius: 7,
    // elevation: 4,
    shadowOpacity: 1,
    position: 'absolute',
    left: 0,
    right: 0,
    top: 50,
    bottom: -50,
    // zIndex: 1,
  },
  taskNameText: {
    color: 'black',
    // fontFamily: "Poppins-Regular",
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '500',
    textAlign: 'center',
    letterSpacing: 0.21,
    backgroundColor: 'transparent',
    alignSelf: 'stretch',
    marginRight: 156,
    width: '100%',
  },
  tasktextboxView: {
    alignSelf: 'center',
    width: '85%',
    // alignSelf: 'stretch',
    marginTop: 10,
  },
  getDressedTextInput: {
    backgroundColor: 'transparent',
    padding: 0,
    color: 'black',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
    marginLeft: 11,
    marginRight: 11,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: 'rgba(7, 40, 64, 0.08)',
    borderStyle: 'solid',
    alignSelf: 'stretch',
    height: 85,
    paddingLeft: 5,
    // marginTop: 10,
  },
  approximateTaskLenText: {
    color: 'black',
    // fontFamily: "Rubik-Regular",
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '500',
    textAlign: 'center',
    backgroundColor: 'transparent',
    padding: 5,
  },
  counterView: {
    backgroundColor: '#7A5FFA',
    borderRadius: 25,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowRadius: 29,
    shadowOpacity: 1,
    width: 163,
    height: 52,
    marginTop: 17,
    elevation: 1,
  },
  textFieldView: {
    backgroundColor: 'white',
    width: 73,
    height: 52,
  },
  buttonTwoButton: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingRight: 8,
    paddingBottom: 10,
    width: 25,
    height: 50,
  },
  buttonTwoButtonImage: {
    resizeMode: 'contain',
    marginRight: 10,
  },
  buttonTwoButtonText: {
    color: 'white',
    // fontFamily: "Rubik-Regular",
    fontSize: 42,
    fontStyle: 'normal',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  buttonButtonText: {
    color: 'white',
    // fontFamily: "Rubik-Regular",
    fontSize: 42,
    fontStyle: 'normal',
    fontWeight: 'bold',
    textAlign: 'left',
  },
  buttonButton: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    width: 25,
    height: 50,
  },
  buttonButtonImage: {
    resizeMode: 'contain',
    marginRight: 10,
  },
  textInputTextInput: {
    backgroundColor: 'transparent',
    padding: 0,
    color: 'black',
    // fontFamily: "Rubik-Regular",
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: 'bold',
    textAlign: 'center',
    width: 30,
    height: 20,
  },
  minsText: {
    color: 'black',
    // fontFamily: "Rubik-Regular",
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '300',
    textAlign: 'center',
    backgroundColor: 'transparent',
    marginTop: 3,
    width: 40,
  },
  deletebuttonButtonText: {
    color: '#7A5FFA',
    // fontFamily: "Poppins-Regular",
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '500',
    textAlign: 'left',
  },
  deletebuttonButtonAnimated: {
    width: 80,
    height: 31,
    marginBottom: 20,
  },
  deletebuttonButton: {
    backgroundColor: '#F8F6FF',
    borderRadius: 12,
    // borderWidth: 2,
    borderColor: 'rgb(252, 102, 129)',
    borderStyle: 'solid',
    shadowColor: 'rgba(14, 144, 185, 0.28)',
    shadowRadius: 3,
    elevation: 2,
    shadowOffset: {
      height: 2,
    },
    shadowOpacity: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    width: '100%',
    height: '100%',
  },
  deletebuttonButtonImage: {
    resizeMode: 'contain',
    marginRight: 10,
  },
  savebuttonButtonImage: {
    resizeMode: 'contain',
    marginRight: 10,
  },
  savebuttonButtonAnimated: {
    width: 234,
    height: 46,
  },
  savebuttonButton: {
    backgroundColor: '#7A5FFA',
    borderRadius: 23,
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowRadius: 15,
    shadowOpacity: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    width: '100%',
    height: '100%',
    elevation: 4,
  },
  savebuttonButtonText: {
    color: 'rgb(250, 252, 252)',
    // fontFamily: "Poppins-Regular",
    fontSize: 26,
    fontStyle: 'normal',
    fontWeight: '500',
    textAlign: 'left',
  },
});

export default styles;
