//
//  SettingsScreenStyleSheet.js
//  RiseApp
//
//  Created by Nikhil Patel.
//  Copyright © 2018 Rise. All rights reserved.
//

import {StyleSheet} from 'react-native';

const labelColor = 'black';
const textColor = '#2969FB';
const lineColor = '#7A5FFA';
const buttonColor = '#7A5FFA';

const styles = StyleSheet.create({
  settingsscreenView: {
    backgroundColor: '#DEE9FD', //"rgb(231, 238, 251)",
    flex: 1,
  },
  settingsText: {
    backgroundColor: 'transparent',
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowRadius: 4,
    elevation: 4,
    shadowOpacity: 1,
    color: 'rgb(29, 103, 153)',
    // fontFamily: "Rubik-Regular",
    fontSize: 48,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
    marginTop: 55,
  },
  rectangleView: {
    backgroundColor: '#fff',
    borderRadius: 41,
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowRadius: 15,
    elevation: 4,
    shadowOpacity: 1,
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: -50,
  },
  option1Button: {
    backgroundColor: '#DEE9FD', //"rgb(231, 238, 251)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#dddddd',
    shadowColor: 'rgba(14, 144, 185, 0.20)',
    shadowOffset: {
      height: 2,
    },
    shadowRadius: 10,
    elevation: 4,
    shadowOpacity: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    height: 70,
    marginLeft: 12,
    marginRight: 11,
    zIndex: 1,
  },
  option1ButtonText: {
    color: 'rgb(7, 40, 64)',
    // fontFamily: "Rubik-Regular",
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  option1ButtonImage: {
    resizeMode: 'contain',
    marginLeft: 200,
  },
  option2ButtonText: {
    color: 'rgb(7, 40, 64)',
    // fontFamily: "Rubik-Regular",
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  option2Button: {
    backgroundColor: 'rgb(231, 238, 251)',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#dddddd',
    shadowColor: 'rgba(14, 144, 185, 0.20)',
    shadowOffset: {
      height: 2,
    },
    shadowRadius: 10,
    elevation: 4,
    shadowOpacity: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    height: 70,
    marginLeft: 12,
    marginRight: 11,
    marginTop: 15,
    zIndex: 1,
  },
  option2ButtonImage: {
    resizeMode: 'contain',
    marginLeft: 210,
  },
  option3ButtonImage: {
    resizeMode: 'contain',
    marginLeft: 205,
  },
  option4ButtonImage: {
    resizeMode: 'contain',
    marginLeft: 200,
  },
  option3Button: {
    backgroundColor: '#DEE9FD', //"rgb(231, 238, 251)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#dddddd',
    shadowColor: 'rgba(14, 144, 185, 0.20)',
    shadowOffset: {
      height: 2,
    },
    shadowRadius: 10,
    elevation: 4,
    shadowOpacity: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    height: 70,
    marginLeft: 12,
    marginRight: 11,
    marginTop: 15,
    zIndex: 1,
  },
  option4Button: {
    backgroundColor: '#DEE9FD', //"rgb(231, 238, 251)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#dddddd',
    shadowColor: 'rgba(14, 144, 185, 0.20)',
    shadowOffset: {
      height: 2,
    },
    shadowRadius: 10,
    elevation: 4,
    shadowOpacity: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    height: 70,
    marginLeft: 12,
    marginRight: 11,
    marginTop: 15,
    zIndex: 1,
  },
  option3ButtonText: {
    color: 'rgb(7, 40, 64)',
    // fontFamily: "Rubik-Regular",
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  option4ButtonText: {
    color: 'rgb(7, 40, 64)',
    // fontFamily: "Rubik-Regular",
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  adfreebuttonView: {
    backgroundColor: 'transparent',
    height: 70,
    marginLeft: 12,
    marginRight: 12,
    marginBottom: 35,
  },
  combinedShapeButtonText: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  combinedShapeButton: {
    backgroundColor: '#FC6681',
    borderRadius: 20,
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    shadowRadius: 10,
    elevation: 4,
    shadowOpacity: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    height: 70,
  },
  combinedShapeButtonImage: {
    resizeMode: 'contain',
  },
  buyPremiumText: {
    color: 'white',
    // fontFamily: "Poppins-Regular",
    fontSize: 13,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
    letterSpacing: 0.91,
    backgroundColor: 'transparent',
    opacity: 0.7,
    alignSelf: 'flex-start',
    marginTop: 36,
  },
  line3View: {
    backgroundColor: 'rgb(247, 249, 252)',
    width: 1,
    height: 62,
    marginRight: 19,
  },
  ovalView: {
    backgroundColor: 'rgb(135, 199, 255)',
    borderRadius: 29,
    width: 58,
    height: 58,
  },
  goAdFreeText: {
    backgroundColor: 'transparent',
    color: 'white',
    // fontFamily: "Rubik-Regular",
    fontSize: 23,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  textText: {
    backgroundColor: 'transparent',
    color: 'rgb(250, 252, 252)',
    // fontFamily: "Rubik-Regular",
    fontSize: 22,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'center',
    alignSelf: 'center',
    marginTop: 8,
  },
  taskbarView: {
    backgroundColor: 'rgb(250, 252, 252)',
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    shadowRadius: 16,
    elevation: 4,
    shadowOpacity: 1,
    height: 85,
    justifyContent: 'flex-end',
  },
  homeiconButtonText: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  homeiconButton: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    position: 'absolute',
    alignSelf: 'center',
    width: 38,
    top: 19,
    height: 33,
  },
  homeiconButtonImage: {
    resizeMode: 'contain',
  },
  clipboardButton: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    width: 24,
    height: 33,
  },
  clipboardButtonText: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  clipboardButtonImage: {
    resizeMode: 'contain',
  },
  settingsiconButton: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    width: 36,
    height: 37,
  },
  settingsiconButtonImage: {
    resizeMode: 'contain',
  },
  settingsiconButtonText: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  lineCopyButtonImage: {
    resizeMode: 'contain',
  },
  lineCopyButton: {
    backgroundColor: 'rgb(252, 102, 129)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    alignSelf: 'flex-end',
    width: 44,
    height: 4,
    marginTop: 2,
  },
  lineCopyButtonText: {
    color: 'black',
    fontFamily: '.AppleSystemUIFont',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 'normal',
    textAlign: 'left',
  },
  logoutmodalView: {
    backgroundColor: 'rgba(0, 0, 0, 0.44)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalView: {
    backgroundColor: '#DEE9FD', //"rgb(231, 238, 251)",
    borderRadius: 27,
    shadowColor: 'rgba(0, 0, 0, 0.5)',
    shadowRadius: 20,
    elevation: 4,
    shadowOpacity: 1,
    height: 364,
  },
  areYouSureYouWanText: {
    backgroundColor: 'transparent',
    color: textColor,
    // fontFamily: "Rubik-Regular",
    fontSize: 26,
    fontStyle: 'normal',
    fontWeight: '500',
    textAlign: 'left',
    marginLeft: 28,
    marginRight: 28,
    marginTop: 21,
  },
  buttonscontainerView: {
    backgroundColor: 'white',
    borderRadius: 27,
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowRadius: 5,
    elevation: 4,
    shadowOpacity: 1,
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 300,
  },
  yesbuttonButton: {
    backgroundColor: buttonColor,
    borderRadius: 22,
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowRadius: 7,
    elevation: 4,
    shadowOpacity: 1,
    flexDirection: 'row',
    alignItems: 'center',
    shadowOffset: {
      height: 2,
    },
    justifyContent: 'center',
    padding: 0,
    height: 44,
    marginBottom: 34,
  },
  yesbuttonButtonImage: {
    resizeMode: 'contain',
    marginRight: 10,
  },
  yesbuttonButtonText: {
    color: 'white',
    // fontFamily: "Rubik-Regular",
    fontSize: 28,
    fontStyle: 'normal',
    fontWeight: '500',
    textAlign: 'left',
  },
  nobuttonButtonImage: {
    resizeMode: 'contain',
    marginRight: 10,
  },
  nobuttonButton: {
    backgroundColor: '#F4F2FF',
    borderRadius: 16.5,
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowRadius: 3,
    elevation: 4,
    shadowOffset: {
      height: 2,
    },
    shadowOpacity: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    height: 38,
    marginLeft: 29,
    marginRight: 30,
  },
  nobuttonButtonText: {
    color: buttonColor,
    // fontFamily: "Rubik-Regular",
    fontSize: 28,
    fontStyle: 'normal',
    fontWeight: '500',
    textAlign: 'center',
  },
});

export default styles;
