//
//  SetUpProfileStyleSheet.js
//  RiseApp
//
//  Created by Nikhil Patel.
//  Copyright © 2018 Rise. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	setupprofileView: {
		backgroundColor: "rgb(231, 238, 251)",
		flex: 1,
	},
	setUpYourProfileText: {
		color: "rgb(29, 103, 153)",
		// fontFamily: "Rubik-Regular",
		fontSize: 36,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.1)",
		shadowRadius: 4,
		shadowOpacity: 1,
		alignSelf: "center",
		// marginLeft: 31,
	},
	rectangleScrollView: {
		backgroundColor: "white",
		borderRadius: 41,
		shadowColor: "rgba(0, 0, 0, 0.1)",
		shadowRadius: 21,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		bottom: 0,
	},
	selectTheDayFirstText: {
		color: "rgb(29, 103, 153)",
		// fontFamily: "Rubik-Regular",
		fontSize: 24,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
	},
	daypickerView: {
		backgroundColor: "rgba(135, 199, 255, 0.72)",
		borderRadius: 15,
		shadowColor: "rgba(0, 0, 0, 0.35)",
		shadowRadius: 4,
		shadowOpacity: 1,
		width: 333,
		height: 52,
		marginRight: 10
	},
	daybuttonsuView: {
		backgroundColor: "transparent",
		width: 39,
		height: 36,
	},
	ovalButtonText: {
		color: "black",
		fontFamily: ".AppleSystemUIFont",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	ovalButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		height: 36,
	},
	ovalButtonImage: {
		resizeMode: "contain",
	},
	suText: {
		backgroundColor: "transparent",
		color: "white",
		// fontFamily: "Rubik-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		letterSpacing: 1.61,
		marginLeft: 9,
		marginRight: 9,
	},
	daybuttonmView: {
		backgroundColor: "transparent",
		width: 39,
		height: 36,
		marginLeft: 5,
	},
	ovalTwoButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		height: 36,
	},
	ovalTwoButtonText: {
		color: "black",
		fontFamily: ".AppleSystemUIFont",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	ovalTwoButtonImage: {
		resizeMode: "contain",
	},
	mText: {
		color: "white",
		// fontFamily: "Rubik-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		letterSpacing: 1.61,
		backgroundColor: "transparent",
		marginLeft: 13,
		marginRight: 13,
	},
	daybuttontView: {
		backgroundColor: "transparent",
		width: 39,
		height: 36,
		marginLeft: 5,
	},
	ovalThreeButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		height: 36,
	},
	ovalThreeButtonText: {
		color: "black",
		fontFamily: ".AppleSystemUIFont",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	ovalThreeButtonImage: {
		resizeMode: "contain",
	},
	tText: {
		color: "white",
		// fontFamily: "Rubik-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		letterSpacing: 1.61,
		backgroundColor: "transparent",
		marginLeft: 15,
		marginRight: 14,
	},
	daybuttonthView: {
		backgroundColor: "transparent",
		width: 39,
		height: 36,
		marginRight: 5,
	},
	ovalFiveButtonImage: {
		resizeMode: "contain",
	},
	ovalFiveButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		height: 36,
	},
	ovalFiveButtonText: {
		color: "black",
		fontFamily: ".AppleSystemUIFont",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	thText: {
		backgroundColor: "transparent",
		color: "white",
		// fontFamily: "Rubik-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		letterSpacing: 1.61,
		marginLeft: 5,
		marginRight: 5,
	},
	daybuttonfView: {
		backgroundColor: "transparent",
		width: 39,
		height: 36,
		marginRight: 5,
	},
	ovalSixButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		height: 36,
	},
	ovalSixButtonText: {
		color: "black",
		fontFamily: ".AppleSystemUIFont",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	ovalSixButtonImage: {
		resizeMode: "contain",
	},
	fText: {
		backgroundColor: "transparent",
		color: "white",
		// fontFamily: "Rubik-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		letterSpacing: 1.61,
		marginLeft: 14,
		marginRight: 14,
	},
	daybuttonsView: {
		backgroundColor: "transparent",
		width: 39,
		height: 36,
	},
	ovalSevenButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		height: 36,
	},
	ovalSevenButtonText: {
		color: "black",
		fontFamily: ".AppleSystemUIFont",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	ovalSevenButtonImage: {
		resizeMode: "contain",
	},
	sText: {
		color: "white",
		// fontFamily: "Rubik-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		letterSpacing: 1.61,
		backgroundColor: "transparent",
		marginLeft: 14,
		marginRight: 14,
	},
	daybuttonwView: {
		backgroundColor: "transparent",
		width: 39,
		height: 36,
	},
	ovalFourButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		height: 36,
	},
	ovalFourButtonText: {
		color: "black",
		fontFamily: ".AppleSystemUIFont",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	ovalFourButtonImage: {
		resizeMode: "contain",
	},
	wText: {
		color: "white",
		// fontFamily: "Rubik-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		marginLeft: 13,
		marginRight: 13,
	},
	thenFillOutTheFText: {
		color: "rgb(29, 103, 153)",
		// fontFamily: "Rubik-Regular",
		fontSize: 21,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		marginTop: 9,
	},
	infocardView: {
		backgroundColor: "transparent",
		borderRadius: 21,
		borderWidth: 1,
		borderColor: "rgb(135, 199, 255)",
		borderStyle: "solid",
		alignSelf: "stretch",
		height: 366,
		marginLeft: 15,
		marginRight: 28,
		marginTop: 4,
	},
	timepickerView: {
		backgroundColor: "transparent",
		alignSelf: "flex-start",
		width: 112,
		height: 77,
		marginLeft: 12,
		marginTop: 13,
	},
	arrivalTimeText: {
		color: "rgb(29, 103, 153)",
		// fontFamily: "Poppins-Regular",
		fontSize: 18,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		letterSpacing: 0.16,
		backgroundColor: "transparent",
		marginRight: 1,
	},
	textInputTextInput: {
		color: "rgb(29, 103, 153)",
		// fontFamily: "Poppins-Regular",
		fontSize: 36,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		padding: 0,
		height: 46,
		marginLeft: 4,
		marginRight: 1,
		marginTop: 3,
	},
	lineView: {
		backgroundColor: "rgb(135, 199, 255)",
		height: 1,
	},
	destinationView: {
		backgroundColor: "transparent",
		height: 56,
		marginLeft: 12,
		marginRight: 15,
		marginTop: 24,
	},
	destinationText: {
		backgroundColor: "transparent",
		color: "rgb(29, 103, 153)",
		// fontFamily: "Poppins-Regular",
		fontSize: 18,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		letterSpacing: 0.16,
	},
	addressTextInput: {
		color: "rgb(29, 103, 153)",
		// fontFamily: "Poppins-Regular",
		fontSize: 18,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		padding: 0,
		alignSelf: "stretch",
		height: 35,
		marginLeft: 7,
	},
	rectangleView: {
		backgroundColor: "transparent",
		borderRadius: 3,
		borderWidth: 1,
		borderColor: "rgb(135, 199, 255)",
		borderStyle: "solid",
		position: "absolute",
		left: 0,
		right: 3,
		top: 26,
		height: 30,
	},
	currentlocationView: {
		backgroundColor: "transparent",
		height: 56,
		marginLeft: 12,
		marginRight: 15,
		marginTop: 24,
	},
	startLocationText: {
		color: "rgb(29, 103, 153)",
		// fontFamily: "Poppins-Regular",
		fontSize: 18,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		letterSpacing: 0.16,
		backgroundColor: "transparent",
	},
	addressTwoTextInput: {
		color: "rgb(29, 103, 153)",
		// fontFamily: "Poppins-Regular",
		fontSize: 18,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		padding: 0,
		alignSelf: "stretch",
		height: 35,
		marginLeft: 7,
	},
	rectangleTwoView: {
		backgroundColor: "transparent",
		borderRadius: 3,
		borderWidth: 1,
		borderColor: "rgb(135, 199, 255)",
		borderStyle: "solid",
		position: "absolute",
		left: 0,
		right: 0,
		top: 26,
		height: 30,
	},
	transmodeView: {
		backgroundColor: "transparent",
		alignSelf: "center",
		width: 264,
		height: 83,
		marginBottom: 11,
		alignItems: "flex-start",
	},
	transportionModeText: {
		color: "rgb(29, 103, 153)",
		// fontFamily: "Rubik-Regular",
		fontSize: 18,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		letterSpacing: 0.16,
		backgroundColor: "transparent",
		marginLeft: 2,
	},
	rectangleThreeView: {
		backgroundColor: "rgba(135, 199, 255, 0.51)",
		borderRadius: 13,
		shadowColor: "rgba(0, 0, 0, 0.33)",
		shadowRadius: 7,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 50,
	},
	carButtonImage: {
		resizeMode: "contain",
	},
	carButton: {
		backgroundColor: "rgb(231, 238, 251)",
		borderRadius: 22.5,
		shadowColor: "rgba(0, 0, 0, 0.25)",
		shadowRadius: 9,
		shadowOpacity: 1,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		width: 45,
		height: 45,
	},
	carButtonText: {
		color: "black",
		fontFamily: ".AppleSystemUIFont",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	trainButton: {
		backgroundColor: "rgb(231, 238, 251)",
		borderRadius: 22.5,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		width: 45,
		height: 45,
		marginLeft: 19,
	},
	trainButtonText: {
		color: "black",
		fontFamily: ".AppleSystemUIFont",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	trainButtonImage: {
		resizeMode: "contain",
	},
	bikingButtonImage: {
		resizeMode: "contain",
	},
	bikingButton: {
		backgroundColor: "rgb(231, 238, 251)",
		borderRadius: 22.5,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		width: 45,
		height: 45,
		marginRight: 19,
	},
	bikingButtonText: {
		color: "black",
		fontFamily: ".AppleSystemUIFont",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	walkingButton: {
		backgroundColor: "rgb(231, 238, 251)",
		borderRadius: 22.5,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		width: 45,
		height: 45,
	},
	walkingButtonText: {
		color: "black",
		fontFamily: ".AppleSystemUIFont",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	walkingButtonImage: {
		resizeMode: "contain",
	},
	nextbuttonButtonImage: {
		resizeMode: "contain",
	},
	nextbuttonButton: {
		backgroundColor: "rgb(252, 102, 129)",
		borderRadius: 27.5,
		shadowColor: "rgba(0, 0, 0, 0.25)",
		shadowRadius: 15,
		shadowOpacity: 1,
		// flexDirection: "row",
		// alignItems: "flex-end",
		// justifyContent: "flex-end",
		paddingTop: 10,
		left: '40%',
		width: 55,
		height: 55,
	},
	nextbuttonButtonText: {
		color: "rgb(250, 252, 252)",
		// fontFamily: "Poppins-Regular",
		fontSize: 24,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	savebuttonButton: {
		backgroundColor: "rgb(252, 102, 129)",
		borderRadius: 23,
		shadowColor: "rgba(0, 0, 0, 0.25)",
		shadowRadius: 15,
		shadowOpacity: 1,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		position: "absolute",
		alignSelf: "center",
		width: 200,
		bottom: 25,
		height: 46,
	},
	savebuttonButtonText: {
		color: "rgb(250, 252, 252)",
		// fontFamily: "Poppins-Regular",
		fontSize: 24,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	savebuttonButtonImage: {
		resizeMode: "contain",
		marginRight: 10,
	},
})

export default styles
